name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt test

    - name: Run App
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sbt run